import Head from 'next/head'
// import Link from 'next/link';
import { useEffect, useState } from 'react';
import postStyles from '../styles/Post.module.css'

export default function Home() {

  const [posts, setPosts] = useState([])

  async function getContents() {
    const res = await fetch('http://localhost:3000/api/posts').then(res => res.json())
    setPosts(res.posts)
  }

  useEffect(() => {
    getContents()
  }, [])

  return (
    <div>
      <Head>
        <title>App Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>App Title {posts.length}</h1>

        {posts.length > 0 && (
          <ul className={postStyles.postlist}>
            {posts.map(post => (
              <li key={post.slug}>
                <a href={'#'}>
                  <img src={post.feature_image} />
                  <div className={postStyles.title}><span>{post.title}</span></div>
                </a>
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  )
}