import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

async function getPost(slug) {
  const res = await fetch(`http://localhost:3000/api/post?slug=${slug}`).then((res) => res.json());
  return res.post;
}

export const getStaticProps = async ({ params }) => {
  console.log(`params:${params}`);
  const post = await getPost(params.slug);
  return {
    props: { post },
    revalidate: 10,
  };
};
export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: true,
  };
};

export default function Post(props) {
  const { post } = props;
  const router = useRouter();

  if (router.isFallback) {
    return <h1>Loading...</h1>;
  }

  return (
    <div>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/">
        <a>戻る</a>
      </Link>

      <main>
        <h1>{post.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.html }}></div>
      </main>
    </div>
  );
}
